const fs = require('fs');
let content = fs.readFileSync('app/api/quotes/[id]/pdf/route.ts', 'utf8');

const oldMerge = '    // Fetch and merge brochures\n    for (const quoteBrochure of quote.brochures) {\n      const brochureUrl = quoteBrochure.brochure.file_url;\n      try {\n        let brochureBuffer: Buffer | null = null;\n        \n        // If it\\'s a URL, fetch it. Otherwise assume local public path (for testing/legacy)\n        if (brochureUrl.startsWith(\\'http\\')) {\n          const response = await fetch(brochureUrl);\n          if (response.ok) {\n            brochureBuffer = Buffer.from(await response.arrayBuffer());\n          } else {\n            console.error(Failed to fetch brochure from );\n          }\n        } else {\n          // Local fallback\n          const localPath = path.join(process.cwd(), \\'public\\', brochureUrl);\n          if (fs.existsSync(localPath)) {\n             brochureBuffer = fs.readFileSync(localPath);\n          }\n        }\n\n        if (brochureBuffer) {\n          const brochureDoc = await PDFDocument.load(brochureBuffer);\n          const copiedPages = await pdfDoc.copyPages(brochureDoc, brochureDoc.getPageIndices());\n          copiedPages.forEach((page) => {\n            pdfDoc.addPage(page);\n          });\n        }\n      } catch (err) {\n        console.error(Error merging brochure from , err);\n      }\n    }';

const newMerge = '    // Fetch and merge brochures\n    for (const quoteBrochure of quote.brochures) {\n      const brochureUrl = quoteBrochure.brochure.file_url;\n      const brochureBase64 = quoteBrochure.brochure.file_base64;\n      try {\n        let brochureBuffer: Buffer | null = null;\n        \n        if (brochureBase64) {\n          brochureBuffer = Buffer.from(brochureBase64, \\'base64\\');\n        } else if (brochureUrl.startsWith(\\'http\\')) {\n          const response = await fetch(brochureUrl);\n          if (response.ok) {\n            brochureBuffer = Buffer.from(await response.arrayBuffer());\n          } else {\n            console.error(Failed to fetch brochure from );\n          }\n        } else {\n          // Local fallback\n          const localPath = path.join(process.cwd(), \\'public\\', brochureUrl);\n          if (fs.existsSync(localPath)) {\n             brochureBuffer = fs.readFileSync(localPath);\n          }\n        }\n\n        if (brochureBuffer) {\n          const brochureDoc = await PDFDocument.load(brochureBuffer);\n          const copiedPages = await pdfDoc.copyPages(brochureDoc, brochureDoc.getPageIndices());\n          copiedPages.forEach((page) => {\n            pdfDoc.addPage(page);\n          });\n        }\n      } catch (err) {\n        console.error(Error merging brochure from , err);\n      }\n    }';

content = content.replace(oldMerge, newMerge);
fs.writeFileSync('app/api/quotes/[id]/pdf/route.ts', content);
console.log('Modified PDF route');

